### ISSUE TITLE
Feature request: tweakable shader uniforms with dat.GUI

### ISSUE THREAD

**Issue by visy** [patuwwy/ShaderToy-Chrome-Plugin#1]

**Comment by movAX13h** [comment]
Those shaders wont be compatible with shadertoy (custom uniforms) ... so I think this is a bad idea.

**Comment by patuwwy** [comment]
There are some nice proposals on [pouet](http://www.pouet.net/topic.php?which=10696&page=1#c513748)

This feature is analysed.

**Comment by patuwwy** [comment]
Additional uniforms are not allowed due to 'clean' Shadertoy incompatibility.
