### ISSUE TITLE
problematic redirect after login 

### ISSUE THREAD

**Issue by movAX13h** [patuwwy/ShaderToy-Chrome-Plugin#10]
Hi Patu!
I've seen that the original redirect after login on shadertoy does not work properly **if the plugin is enabled**. I think they are using the **last requested URL** to redirect back after a successful login. The plugin somehow makes https://www.shadertoy.com/img/topbackground.png the last request and so st redirects to this file after login.

**Comment by patuwwy** [comment]
Confirmed. 
It seems that Shadertoy is already being prepared to introduce color themes. There were plans about it. Images location changed. The solution for now is to remove requested background image from css for dark theme, which bug affects.

**Comment by patuwwy** [comment]
oh, Just noticed they are already implemented dark theme :)

**Comment by movAX13h** [comment]
Ah right... they must have added this recently... it was not there when I did the German translation.
