### ISSUE TITLE
[BUG] timers don't display in fullscreen

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#107]
**Describe the bug**
the feature displaying ms don't display in fullscren.

(note that in fullscren you might also display fsp as well, since the info is no longer there to )

**Comment by patuwwy** [comment]
Yes, this is how it works because of shadertoy brings only canvas element to fullscreen.
Original behavior needs to be replaced to display other stuff like ms/fps.

**Comment by pxv8270** [comment]
For me the gpu render ms aren't even displaying in window/canvas mode even though console says "EXT_disjoint_timer_query_webgl2" was found. I'm on chrome 64 build 80.0.3987.132.

**Comment by FabriceNeyret** [comment]
I got the error recently too, but it seems gone. Probably a problem with a temporary update of Chrome.
Or it works on my home machine because it is late by one update or reboot compare to my lab machine :-)

**Comment by pxv8270** [comment]
Out of curiosity, what version of chrome are you running where the gpu render time display works?

**Comment by FabriceNeyret** [comment]
80.0.3987.132 linux 64bits.

**Comment by pxv8270** [comment]
That's strange! I'm on the same chrome build, but on win10 64bit. Could this be a windows specific bug?

**Comment by FabriceNeyret** [comment]
have you tried quitting (really totally) then relaunching ? Chrome has a fallback mode that emulates webGL instead of using the GPU in case of series of error.  What about rebooting ?
Have you tried to inspect your webGL state with https://webglreport.com/?v=2 ?

**Comment by patuwwy** [comment]
> That's strange! I'm on the same chrome build, but on win10 64bit. Could this be a windows specific bug?

Works for me on Chrome 80, Win10 64bit

**Comment by pxv8270** [comment]
@FabriceNeyret Yup tried all of those things already. :) The webgl report tells me everything's supported on my 1070 gpu. No errors in chrome console as well. Completely stumped as to why it's not rendering. 

@patuwwy Chrome console says, "Found EXT_disjoint_timer_query_webgl2 extension" but I still don't get any overlay timer display. Any guesses what could be causing it to not render?

**Comment by patuwwy** [comment]
@pxv8270 When you press the timer icon, does it turn blue?

**Comment by pxv8270** [comment]
Well this is embarrassing! I never actually paid any attention to the timer icon and just noticed it after seeing you mention it. Pressing that displayed the timer overlay, thanks a bunch! And extremely sorry for wasting everyone's time!

**Comment by patuwwy** [comment]
Don't be sorry, it was the first thought that came to my mind that you might not have activated it :)

**Comment by pxv8270** [comment]
Haha, thanks for pointing it out! :)

**Comment by pixelsnafu** [comment]
Hey! The timer has stopped working for me lately, and this time I thoroughly checked and the plugin is unable find the EXT_disjoint_timer_query_webgl2 on my browser any more. Did something change?

![EXT_disjoint_timer_query_webgl2 not found](https://user-images.githubusercontent.com/3968793/95580824-98fac000-0a55-11eb-8a46-6bfb7f275237.png)

**Comment by patuwwy** [comment]
It seems shadertoy changed place where context is stored. 
Fixed in #113

**Comment by pixelsnafu** [comment]
It's working again now! Thanks a bunch! :)
