### ISSUE TITLE
request: clone any shader

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#11]
you permit to clone our own shader. But it would be very useful too allow clowning any shaders, not only ours.

**Comment by patuwwy** [comment]
This feature is done already as a side affect of import/export shader feature. (waiting to be deployed)
You can export any shader and then import it (new shader, then import)

Of course, this is not final solution for this issue.
One click clone will be.

**Comment by patuwwy** [comment]
FYI: import/export shader has been released.

**Comment by patuwwy** [comment]
Waits to be released.

**Comment by patuwwy** [comment]
Released just now.
