### ISSUE TITLE
[BUG] ALT-2 doesn't work anymore on my PC

### ISSUE THREAD

**Issue by kastorp73** [patuwwy/ShaderToy-Chrome-Plugin#114]
since a couple of weeks on my PC the ALT-1...9 doesn't have effect anymore
inspecting with chrome developer tools I get this exception:

Uncaught TypeError: gShaderToy.resize is not a function
    at ToyPlugEditPage.decreaseRes (shadertoy-plugin.js:310)
    at HTMLDocument.<anonymous> (shadertoy-plugin.js:358)

**Comment by patuwwy** [comment]
This is caused by ShaderToy internal API change.
I will take a look if workaround is possible.

**Comment by patuwwy** [comment]
#117
