### ISSUE TITLE
suggestion: emergency connection

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#12]
very often, shadertoy disconnect while we are modifying code.
worse: sometime we forgot to log in and we cannot save our new shader (very painful if multiple buffers and textures).
-> it would be very useful to have a "(re)connect" button

**Comment by patuwwy** [comment]
When session expires I open Shadertoy in new tab, log in, close tab and save shader :)
Are You thinking about button which checks that You are logged and if so it makes title/tags/ etc editable and shows save button?

**Comment by FabriceNeyret** [comment]
2nd sentence: if you mean, when the buttons are absent because we were not logged when creating or edting this shader, then yes !

1st sentence: yep but this is still a bit annoying. But ok, a lot less than the other case above.

**Comment by patuwwy** [comment]
Made it "on hold" as Shadertoy improved to keep being logged.

**Comment by patuwwy** [comment]
Shadertoy has imporved session keeping. 
I'm closing this issue
