### ISSUE TITLE
[BUG] Import is broken on Firefox

### ISSUE THREAD

**Issue by Boscop** [patuwwy/ShaderToy-Chrome-Plugin#122]
**Describe the bug**
It seems like the recent update just broke the import button (only in Firefox), it was working a few hours ago. Now it doesn't open the file chooser dialog anymore, so i can't import my shader:

![image](https://user-images.githubusercontent.com/535593/101205858-87592180-366e-11eb-9382-568fdab4ef70.png)

**To Reproduce**
1. Open Firefox
2. Go to https://www.shadertoy.com/new
3. Click on `Import`
4. See the behavior

**Expected behavior**
File chooser dialog should open, it works in chromium

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser: Firefox

**Additional context**
For each click on `Import`, it shows another `[Browse] No file selected.` element.

**Comment by patuwwy** [comment]
Please confirm with version 0.13.228
