### ISSUE TITLE
[BUG] Exported and re-imported shaders get saved as new shaders with new ID instead of being updated & keeping their ID

### ISSUE THREAD

**Issue by Boscop** [patuwwy/ShaderToy-Chrome-Plugin#123]
**Describe the bug**
When I export a shader for local editing (in my own tool), and then import it again (on the page of that shader `/view/<ID>`), it gets assigned a new idID instead of updating the shader with the imported changed version! 
This shouldn't happen. 
Can you please allow keeping the id for edited & re-imported shaders? 
In the extension, upon clicking `Import`, you can check if the ID of the shader that's currently loaded in the editor (the id in the url) is equal to the ID of the imported shader, and then don't set the id to `-1` (which would assign a new id) but keep the original id. Please :)

**To Reproduce**
1. Go to `https://www.shadertoy.com/view/<ID>` (one of your shaders. login first)
2. Click on `Export`
3. Edit json file (e.g. change the code, or name/description)
4. Click on `Import`
5. Save shader
6. A new shader with new id gets created, instead of updating the original one with the changed version.

**Expected behavior**
Save changes as if they were done on Shadertoy itself.

**Comment by patuwwy** [comment]
should be fixed since https://github.com/patuwwy/ShaderToy-Chrome-Plugin/releases/tag/0.13.228
