### ISSUE TITLE
[BUG]color picker on *vec3

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#125]
color picker on vec3 is cool ( and could be extended to the r,b,g components of vec4.
But applying it to ivec3, bvec3, uvec3 looks like a wrong id ;-)

**Comment by EthanLowenthal** [comment]
Can you expand? On ivec3,bvec3,and uvec3 it works just like normal vec3. Did you want a different behavior?

**Comment by EthanLowenthal** [comment]
Ok I just disabled it on those because it will always give you rgb values <1 and ivec3 and uvec3 will floor to 0 and bvec3 doesnt have r,g,b.
