### ISSUE TITLE
[BUG] Import button creates multiple Image passes:

### ISSUE THREAD

**Issue by Boscop** [patuwwy/ShaderToy-Chrome-Plugin#126]
**Describe the bug**
I import my shader and it creates additional Image pass tabs.
This is bad because I can't manually delete the additional Image pass tabs, so they get saved when I save my shader!
E.g. I saved this shader here, and I still can't remove the additional image passes:
https://www.shadertoy.com/view/tdVfz3

**To Reproduce**
1. Go to /new
2. Click on `Import`, and import the attached shader
3. See 2 image pass tabs
4. Again: Click on `Import`, and import the attached shader
5. See 3 image pass tabs
.. Repeat: See more and more image pass tabs ..

Note: It's impossible to import the attached shader so that it only has 1 image pass tab.

**Expected behavior**
Replace the image pass.

**Screenshots**
![image](https://user-images.githubusercontent.com/535593/101845894-1030fb00-3b50-11eb-98b0-32a14d492edc.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser chromium
 - Version 86.0.4240.75 (Official Build) (64-bit)

**Additional context**
Import this shader.json:

[raymarch.zip](https://github.com/patuwwy/ShaderToy-Chrome-Plugin/files/5676377/raymarch.zip)

**Comment by Boscop** [comment]
Btw, the same happens when I fork another shader! It has an additional image pass tab.

**Comment by Boscop** [comment]
This is the same bug: https://github.com/patuwwy/ShaderToy-Chrome-Plugin/issues/127

**Comment by patuwwy** [comment]
Should be ok since https://github.com/patuwwy/ShaderToy-Chrome-Plugin/releases/tag/0.13.228
