### ISSUE TITLE
[BUG] fork creates 2 Images tab

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#127]
only for some shaders, like this one: https://www.shadertoy.com/view/wstyzl

it combine the default shader with the forked shader. 
( maybe it's connected to the recent reorganisation of shadertoy )

**Comment by FabriceNeyret** [comment]
I thought yesterday that it was solved, but no.
This one is a really blocking bug :-(

**Comment by Zi7ar21** [comment]
I just replace the image buffer the extension makes with
```glsl
// dang shadertoy extension broke
void mainImage(out vec4 fragColor, in vec2 fragCoord){}

**Comment by FabriceNeyret** [comment]
> I just replace the image buffer the extension makes with

it's useless since Shadertoy now refuse to save shaders having 2 images tabs.

**Comment by patuwwy** [comment]
#129
