### ISSUE TITLE
[BUG] buttons Fork, Export,  ExportZip no longer working

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#134]
buttons are there, but do nothing (neither or mine or others shaders)
other buttons still work.

**Comment by patuwwy** [comment]
ShaderToy API has been changed. 
Extensions needs update.

**Comment by FabriceNeyret** [comment]
how do I do that ? 
clearing cache + shift- or ctrl- reload + relaunching chrome doesn't fix it.

**Comment by patuwwy** [comment]
I mean that extension needs changes :)
Please be patient. I will try to fix it asap
