### ISSUE TITLE
[BUG] Fork now loose title, tags, description 

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#139]
Fork now loose title, tags, description.

**Comment by patuwwy** [comment]
fixed

**Comment by FabriceNeyret** [comment]
nope, not fixed (even after rebooting my machine).

**Comment by patuwwy** [comment]
what browser?

**Comment by FabriceNeyret** [comment]
chrome. plugin version v0.13.242 ( isn't it supposed to auto-update ? otherwise, how do I update ? )
