### ISSUE TITLE
[BUG] auto-clickable URL no longer working

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#140]
auto-clickable URL in forums are no longer working

**Comment by patuwwy** [comment]
please provide example.
Links on https://www.shadertoy.com/view/llBcR1 still work.

**Comment by FabriceNeyret** [comment]
strange: it's when I post the link that all links in the forum are no longer clickable.
But it I reload everything is clickable, including the last entered.

**Comment by patuwwy** [comment]
That's how it was implemented

**Comment by FabriceNeyret** [comment]
I'm not sure you understand my point:

before adding a link:
![image](https://user-images.githubusercontent.com/13150247/103745917-92ea9000-5000-11eb-9255-f951ece40b55.png)

after adding the link:
![image](https://user-images.githubusercontent.com/13150247/103745963-a4339c80-5000-11eb-9095-edeaefa9833a.png)

then after reloading the page, all is fixed.
