### ISSUE TITLE
about Fork

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#141]
Note that iq has now implemented a "fork" feature, but I still prefer yours ( i.e. insert header, don't save yet, preserve metadata ) : so, please keep it :-)

( but you might still fix the bug about all meta-data now lost: https://github.com/patuwwy/ShaderToy-Chrome-Plugin/issues/139  :-D )

**Comment by patuwwy** [comment]
can't see this new option. where it is?

**Comment by FabriceNeyret** [comment]
when logged, this is this new icon just below yours ;-)
![image](https://user-images.githubusercontent.com/13150247/106710193-d6cbb780-65f5-11eb-9fbc-4eb01d330639.png)
