### ISSUE TITLE
Suggestion: Resolution upscale

### ISSUE THREAD

**Issue by MichaelMoroz** [patuwwy/ShaderToy-Chrome-Plugin#155]
Would be nice to have the option to not only divide the resolution, but also increase it. It's mostly useful for better quality and benchmarking.

On top of Alt + 1..9 for downscale something like Ctrl + 1..9 or Alt+Shift+1...9 for upscale would be nice.

**Comment by 589290** [comment]
Aye, I would love to be able to change the canvas to 3840x2160 so-as to record the output in 4K

**Comment by 589290** [comment]
It turns out... all you have to do is open dev tools and execute something like this to change the canvas res :
```
gShaderToy.iSetResolution(3840,2160);
```
But still, it would be nice to have this as a feature under Toggle Controls somewhere....

**Comment by 589290** [comment]
Actually, it's a little more involved.... see: https://github.com/patuwwy/ShaderToy-Chrome-Plugin/blob/7a87138bc6152ac1d13168abf08887c797fea75b/app/shadertoy-plugin.js#L319 but this works :
```
// change ST res

var mE = gShaderToy.mEffect;
var xres = 3840;
var yres = 2160;

gShaderToy.mEffect.mRO.unobserve(gShaderToy.mCanvas);

mE.mCanvas.setAttribute('width', xres);
mE.mCanvas.setAttribute('height', yres);
mE.mCanvas.width = xres;
mE.mCanvas.height = yres;
mE.mXres = xres;
mE.mYres = yres;

mE.ResizeBuffers(xres, yres);

gShaderToy.iSetResolution(xres, yres);
```

**Comment by patuwwy** [comment]
https://github.com/patuwwy/ShaderToy-Chrome-Plugin/commit/bad34b2cb344991740468f5253a7abe4fa0f7884#diff-97ddfbfdfa28160edf2fd79875298303d289ec4c5d4f468354af104d55c78867R384
