### ISSUE TITLE
Update the preview image

### ISSUE THREAD

**Issue by mdb0** [patuwwy/ShaderToy-Chrome-Plugin#158]
I don't think there is currently a way to update the image of the preview image and I think it would be nice to be able to control when the preview image is taken.
It can be a button that loads the current rendered image as a preview image.

**Comment by patuwwy** [comment]
In fact, the preview is updated with every shader save. You can check this by forcing the cache bypass using Ctrl + Shift + R in Chrome, try with https://www.shadertoy.com/media/shaders/SHADER_ID.jpg
