### ISSUE TITLE
Inlay errors in Monaco editor.

### ISSUE THREAD

**Issue by wrightwriter** [patuwwy/ShaderToy-Chrome-Plugin#167]
The ErrorLens VSCode extension provides this:
![image](https://github.com/patuwwy/ShaderToy-Chrome-Plugin/assets/8731857/ccfca349-0546-4fba-817f-4954fd7cab1c)
But it's not available in monaco.
The alternative, i'm guessing, is to do something like this - https://stackoverflow.com/questions/71148337/monaco-editor-how-do-i-get-the-error-message-to-pop-out-instead-of-displaying-i  
![image](https://github.com/patuwwy/ShaderToy-Chrome-Plugin/assets/8731857/dd2c6eb8-5968-40e0-8c31-35378b28067b)
Does the shadertoy API provide the list of errors? 🤔

**Comment by wrightwriter** [comment]
Yeah, seems like gShaderToy has the list of errors.
![image](https://github.com/patuwwy/ShaderToy-Chrome-Plugin/assets/8731857/0ad7ff52-a776-40f5-9dcd-ceea901b0c10)

**Comment by wrightwriter** [comment]
i believe monaco "decorations" can be used to display errors?

**Comment by patuwwy** [comment]
![image](https://github.com/patuwwy/ShaderToy-Chrome-Plugin/assets/3254964/a1b94669-e715-46d7-b6dd-8a85b7936409)

**Comment by wrightwriter** [comment]
not what i had in mind

**Comment by wrightwriter** [comment]
this is only on mouse over
