### ISSUE TITLE
suggestion: clickable url

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#17]
many people forget to make url clickable in description and forums. would be cool to make them clickable.

**Comment by patuwwy** [comment]
Need some example shaders with not marked urls in description and comments.

**Comment by FabriceNeyret** [comment]
what means tag "question" here ?

**Comment by patuwwy** [comment]
I need a set of shaders with urls  in description and/or forums to develop this feature. Could You do provide such a set?

**Comment by FabriceNeyret** [comment]
just for your eyes ;-) : https://www.shadertoy.com/view/llBcR1

**Comment by patuwwy** [comment]
Got it working. 
NB, What about making links more visible by changing the color? 
now, links are just bolder.
IMO, links should be underlined, not bold, and have different color.

**Comment by FabriceNeyret** [comment]
The most important is that they get clickable.
Then, why not changing the style if you like, as long as there is no look difference with already clickable links. (excepted  if you want to stress about "this link was offered by the plugin" ;-) )
Attention: shadertoy allow to switch between clear and dark skins, so it can be risky to play with text colors.

**Comment by FabriceNeyret** [comment]
thanks for the feature, but with sky-blue text upon grey background I can no longer read links ;-)
( using default skin and approximate monitor gamma tuning )

**Comment by patuwwy** [comment]
I know. Color change is restored already and will be released ASAP.
