### ISSUE TITLE
Reset resolution

### ISSUE THREAD

**Issue by XorDev** [patuwwy/ShaderToy-Chrome-Plugin#183]
It'd be nice if ALT+0 reset back to the original resolution. Once I change a resolution, None of the settings go back to the original resolution

**Comment by patuwwy** [comment]
ALT+1 is default resolution. I don't see any issues. Please provide steps to reproduce.

**Comment by XorDev** [comment]
In my testing, if the original resolution is 1200x675, then ALT+1 is 800x450, ALT+2 is 400x225 and so on.
Upon further testing I've found that scaling ShaderToy's website to 67% fixes it, so it appears to not be factoring in webscaling? I'm using a 4k monitor, so that may be displaying at a different scale. Zooming to 200% makes ALT+1 far further from the original
