### ISSUE TITLE
[BUG] many error warnings / "soon not supported in Chrome"

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#188]
Hi !
Chrome says that the marvelous plugin will no longer be supported.
Here are the warnings mentionned for the extension:
......................................................................
Manifest version 2 is deprecated, and support will be removed in 2024. See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details.

Uncaught ReferenceError: CodeMirror is not defined
TypeError: Cannot read properties of null (reading 'insertBefore')
TypeError: Cannot read properties of null (reading 'insertBefore')
Uncaught ReferenceError: CodeMirror is not defined
TypeError: Cannot read properties of null (reading 'insertBefore')
Uncaught ReferenceError: CodeMirror is not defined

**Comment by patuwwy** [comment]
PLease confirm that You are using version 0.14.260 from Chrome Web Store.
Extension is migrated to manifest 3 already https://github.com/patuwwy/ShaderToy-Chrome-Plugin/blob/eb698ee9f9ceeecc70e77baec587fbcba1f4caa5/app/manifest.json#L2

**Comment by FabriceNeyret** [comment]
Nope, alas: 
the current version is hardly usable because of the undo/redo bug is still there, so I have to regress to this old version.

**Comment by patuwwy** [comment]
Old version can cause mentioned warnings.
