### ISSUE TITLE
issue: profile sorting now natively provided by shadertoy

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#19]
If I don't messup, I guess all your sorting entries are now natively provided.
( still, we can't sort draft shaders by date... because they have no date :-( . )

**Comment by patuwwy** [comment]
Possible sorting by shader id can sort shaders by date :)

**Comment by patuwwy** [comment]
Currently implemented sorting options should be removed from plugin if provided natively.

**Comment by FabriceNeyret** [comment]
Uh I missed that, sure sorting by id is would help. But I don't see id displayed ?

**Comment by patuwwy** [comment]
Sorting by ID could be added but after quick test it seems that ID is not date related. 

IMO all sortings should be removed.
