### ISSUE TITLE
in profile, 20% of missing icons for draft/private shaders

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#22]
in profile, 20% of missing icons for draft/private shaders

**Comment by patuwwy** [comment]
Please confirm that your shaders have generated thumbnails https://www.shadertoy.com/media/shaders/YOURSHADERID.jpg

**Comment by FabriceNeyret** [comment]
I verified for a few, and yes, the thumbnails was really missing. Which explains on your side.
