### ISSUE TITLE
suggestion: download all

### ISSUE THREAD

**Issue by movAX13h** [patuwwy/ShaderToy-Chrome-Plugin#24]
For backup reasons (and others) it would be nice to have a button to download all shaders (json files) from the profile - maybe zipped or combined to one big json file. 

What do you think?

**Comment by patuwwy** [comment]
👍 
With this it will be useful to get  also the "restore shader from json" option :)

**Comment by movAX13h** [comment]
Yes, should be doable. I'm working on it. 
Where do I put a function that can be called from edit page and profile page js?

**Comment by movAX13h** [comment]
Ignore my last question ... I put it in ToyPlugCommon prototype and call it via window.ToyPlug.common.

**Comment by patuwwy** [comment]
No, please extract this functionality to new module(file) and name it proper. It seems to be a big set of methods. This module should be loaded by shadertoy-plugin.js. 

Also it  should be reusable by "shader snapshots" feature - load/save from local.

**Comment by movAX13h** [comment]
Ok, I will clean it up ... made it work in a hurry... have to go to bed now. Both, single and complete download are working: https://github.com/movAX13h/ShaderToy-Chrome-Plugin

Single gets json from the shadertoy instance and on the profile page i'm loading 8 at a time, more is not possible on shadertoy side.

**Comment by movAX13h** [comment]
I refactored my code and made a ShaderDownload class for the profile page and put all variables inside, just like you did with TilesView. On the edit page I only added the ToyPlugEditPage.prototype.downloadShader function that adds the button and calls the downloadJson function on click.

The ToyPlug.common.downloadJson function is a helper that gets called from both pages. This is propably not the right location for the code. Please tell me where to put it, then I will do the pull request.

I'm working on the import meanwhile.

**Comment by movAX13h** [comment]
The filename of the profile page download is now username.json, for example: movAX13h.json, the filenames of the single shader downloads are shaderId.json, for example: 4dcGRn.json

Added loading progress display while the script is fetching shader data from the shadertoy server.

**Comment by patuwwy** [comment]
Works like a charm!

**Comment by movAX13h** [comment]
Cool. The import is done too now. I also changed all double quotes and the other remarks you had. Ready for release from my side. I was not sure about the naming and went with Export / Import for the button labels. 

There needs to be some cleanup when the shader is imported, like clearing the comments. How should we proceed here?

**Comment by patuwwy** [comment]
We can not delete existing comments and IMO we should not to do it.
Please convert all tabs to spaces, then make a pull request.

**Comment by movAX13h** [comment]
Sorry, I was not clear: When you are on a shader page where comments are already there and then import a json file, the comments of the previously loaded shader are still visible. I'm just calling the dataLoadShader from shadertoy and then setting the id of the shader to '-1' to avoid overwriting the original one.

Anyway, I replaced all tabs and did the pull request. Thanks!

**Comment by patuwwy** [comment]
[Merged](https://github.com/patuwwy/ShaderToy-Chrome-Plugin/pull/28)
