### ISSUE TITLE
dark color scheme breaks #define cursor

### ISSUE THREAD

**Issue by movAX13h** [patuwwy/ShaderToy-Chrome-Plugin#3]
Somehow with the dark color scheme enabled, code containing #define ... can not be edited properly. (chrome, win8.1)

**Comment by patuwwy** [comment]
This is caused by wrong CSS colors definition. I will release fixed version in 24hrs.

**Comment by patuwwy** [comment]
[Fixed](https://github.com/patuwwy/ShaderToy-Chrome-Plugin/commit/46befc47a5dedf5a4f90f2ae617939d47c5727f2)

**Comment by movAX13h** [comment]
thanks!
