### ISSUE TITLE
suggestion: BBcode buttons

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#33]
a lot of users don't even know about BBcodes in shader forums.
Still, typing [url]...[/url] or code or img  is cumbersome and often prone to typo (and their is no edit or delete button onces sent).

suggestion: below the text entry box for the foum, add buttons for auto-filling (main) BBcodes. 

variant1: just autotyping [code]  [/code]   (with spaces so that it's easy to click at the middle to put content)

variant2: open a requester (especially for url,img,video) and autotype the result

**Comment by EthanLowenthal** [comment]
![Screen Shot 2020-12-18 at 10 00 25 PM](https://user-images.githubusercontent.com/17103654/102682197-8353f600-417c-11eb-96ee-8bae38112d96.png)
I actually thought this was a good idea so I made something like this... I can make a PR but idk if there is enough interest...

**Comment by patuwwy** [comment]
Looks great

**Comment by FabriceNeyret** [comment]
very great !
