### ISSUE TITLE
suggestion: foldable panel for time+mouse control

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#35]
time + mouse control sliders (and especially the later) takes a lot of room in the window while not always used (especially the later).

Suggestion: putting the whole thing (or just the mouse part) in a collapsed <div> with a side button to uncollapse it.

**Comment by patuwwy** [comment]
Agree.

**Comment by FabriceNeyret** [comment]
nicely done :-)
