### ISSUE TITLE
suggestion: at fork, keep track as first comment

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#40]
To ease good practices and solve lack of foreseeing and thinking, I suggest that at fork a first comment line be added tracing the fork. Like, original url, owner, maybe date of fork.

(a clue could be given also on shader title and description, but limited length make it uneasy, and the code itself is the most important anyway).

**Comment by patuwwy** [comment]
comment like this should be ok 

```
/*
 * Fork of:
 * "The Eye" by srtuss
 * https://shadertoy.com/view/Xd2XDm
 */
--- one line break and               ---
--- original shader code starts here ---
```

**Comment by patuwwy** [comment]
0.9.7

**Comment by FabriceNeyret** [comment]
It could also be just one line
 //  Fork of "The Eye" by srtuss : https://shadertoy.com/view/Xd2XDm
+ newline,
much like a log entry. 

not sure which is best :-)

I would also add date of fork. Useful for 
- self use (variants of a project)
- forks at early stage of projects in competitions which will keep evolving.

**Comment by patuwwy** [comment]
Date of fork added in [0.9.8](https://github.com/patuwwy/ShaderToy-Chrome-Plugin/commit/edf9e3cb16dcb1fe8af9b8e6e5f008ce211a3fa6)
