### ISSUE TITLE
Bug: freeze at fork: are itime/iFrame/Buffers reset to 0 .

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#41]
If I fork one on my perfmeter ( like https://www.shadertoy.com/view/lllfz7 ) I freeze and crash webGL.
ok, my perfmeters are special: very costly + test GPU power at first frames.

**Comment by patuwwy** [comment]
It looks like i just have fixed it. 
Fix comes in [0.9.8](https://github.com/patuwwy/ShaderToy-Chrome-Plugin/commit/edf9e3cb16dcb1fe8af9b8e6e5f008ce211a3fa6)
