### ISSUE TITLE
fork erase the original at save !

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#42]
Something horribly wrong happened twice to me today:
after fork, save created the same Id as the original, erasing it !

**Comment by FabriceNeyret** [comment]
safer to test on somebody else shader.
At save, I then get " The shader could not be added, please try again. Error code : 2 "

(note that fork was proposed only once I modified the source).

**Comment by patuwwy** [comment]
fixed, [0.9.9](https://github.com/patuwwy/ShaderToy-Chrome-Plugin/commit/2183c3292840ebec8753b877a3424e1dd712c598)

**Comment by patuwwy** [comment]
I am sorry if you lost your work.

**Comment by FabriceNeyret** [comment]
well, when I saw it today, I could use a backup ( I use the API for wgetting all my shaders from time to time).
But I hope I didn't do it in the past without knowing :-S . Was the bug around since long ?

**Comment by patuwwy** [comment]
broken version has been commited [here](https://github.com/patuwwy/ShaderToy-Chrome-Plugin/issues/41), 3 days ago. 

It has been published later in the store, and chrome also needs several hours to update extension.

So bug has been here from max 2 days.

**Comment by FabriceNeyret** [comment]
ok. No harm for me, then.
