### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by cxw42** [patuwwy/ShaderToy-Chrome-Plugin#46]
patu, thanks for a great tool!  What is the license?  I can't find it anywhere.  MIT?  WTFPL?  CC-BY?  I am working on a pull request for ZIP download (for easier scene.org upload) and would like to make sure I don't incorporate code that's not compatible with your plans.  Thank you!

**Comment by patuwwy** [comment]
[MIT](https://github.com/patuwwy/ShaderToy-Chrome-Plugin/commit/e26a156883569d0cb3159428d0f104acaf61601b)
