### ISSUE TITLE
bug ? profile display

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#55]
in the profile page, iq had added the icon image, then a week ago recently he has "optimized the page".
since, I have the feeling that the plugin can no longer sort by date, type, etc ( run forever ).

**Comment by patuwwy** [comment]
There is no sorting functionality provided by plugin since it has been natively introduced to Shadertoy.

It has been removed in [version 0.8.4](https://github.com/patuwwy/ShaderToy-Chrome-Plugin/commit/177e70dc2163b325708b63622e3745012e3c77cc) released on 4 Aug 2017.
