### ISSUE TITLE
suggestion: accelerating shadertoy ! 

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#60]
rory618 use this excellent trick (see https://www.shadertoy.com/view/WdXSWM ):
when shadertoy is limited by the 60fps rather than by the computation power, calling Paint() 2,10,50 fois per time step largely accelerates the simulations:
javascript:  (function(){if(Effect.prototype.Paint.toString().length>1000){_Paint=Effect.prototype.Paint;} Effect.prototype.Paint = function(...args){for(var i = 0; i < 10; i++){_Paint.apply(this,args);}}})()

to reset to one shadertoy eval per time step: 
javascript:  (function(){if(Effect.prototype.Paint.toString().length>1000){_Paint=Effect.prototype.Paint;} Effect.prototype.Paint = function(...args){_Paint.apply(this,args);}})()

-> you could add buttons  x1 (=reset) x2 x4 x8 x16 x32 
(possibly right to the pause/play button if easy).
Wouldn't it be greaaaat ? :-p

**Comment by R-McHenry** [comment]
Fancy seeing you here, beat me to it :+1: 
To add a few things, maybe optionally call the fps update function as well to show the accelerated framerate. Also this is a good feature along side the resolution scaling, together time scaling and resolution scaling gives you a really nice range of parameters that can be tuned to get a shader running well/with good utilization on any gpu.

**Comment by patuwwy** [comment]
ok. the idea is to add speed selector: x1, x2, x4, x8

**Comment by FabriceNeyret** [comment]
yep !
Note that even for big shaders, x50 was still functional to me ( at least in med-size window ).

The others R-McHenry/rory618 remarks are different features suggestions.

**Comment by patuwwy** [comment]
#61

**Comment by patuwwy** [comment]
published, 0.10.0

**Comment by FabriceNeyret** [comment]
yippee, great !

How do I activate it ? ( relaunching chrome doesn't seem enough ).

**Comment by patuwwy** [comment]
Do you already see this functionality?

**Comment by FabriceNeyret** [comment]
yeees !
hidden in "Toggle controls". ;-)
If it's easy for you to rather make it appear between iTime and FPS, it would be more natural (then no label, just menu " * 1 / * 2 / ... ".   ).
otherwise, it's ok !

**Comment by patuwwy** [comment]
In the meantime, I rewrite most of the extension and try to improve the look and group together the components that the extension provides. I would like all these things to be in one place.

**Comment by FabriceNeyret** [comment]
in one place: you mean, "geographically", for the user  ?
what would be the motivation ? I guess it's better to group what is most cognitively related: 
- in many video players (including youtube) you have a "speed" button in the control bar.
- control of extra inputs ( mouse ) is someting else
- forking, etc, is something else.
If it"s about letting the user identifying what is yours, you already have the "blue signature".

NB: I was about to make the announcement in the facebook forum, but you might intended to do it yourself when you thing it's all good. I think this one is particularly deserve an announcement.

**Comment by FabriceNeyret** [comment]
NB: is label "18" in the menu a typo for "16", or is this one really accelerated 18 times ? ;-p

**Comment by patuwwy** [comment]
> NB: is label "18" in the menu a typo for "16", or is this one really accelerated 18 times ? ;-p

yes and yes :sweat_smile:
