### ISSUE TITLE
Change fork button position.

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#72]
I fought fork button has disappear, but in fact it is now hidden far away of its cousins like "save as new draft". I think it should go back there, especially since we want to encourage people to see and use it (and automatically get the nice safe header), while it's by no way a "control" .

BTW, I see that "save as new draft" doesn't create a header.
Maybe it should, as it's a convenient way to keep some versioning... and to find back the parent shader, since forking/newDraft make it disappear away.

**Comment by patuwwy** [comment]
#87 almost here :)
