### ISSUE TITLE
suggestion: button to see shader precomputed image

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#73]
motivation:

compatibility issues are a nightmare: programmer isn't sure how his shader looks like to other users, and sometime we are not sure that somebody's else shader is really looking as it was intended by its author.

a button showing the image precomputed as the authors saved his shader would allow us to check how it was looking for him. (and to tell him if looking different to what we see).

**Comment by ttoinou** [comment]
Where would it be stored?

**Comment by FabriceNeyret** [comment]
I meant the one already computed by shadertoy. example: https://www.shadertoy.com/media/shaders/4sfGWX.jpg

**Comment by patuwwy** [comment]
#89
