### ISSUE TITLE
[suggestion] longer list for "open recent"

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#75]
"open recent" is a very cool and useful feature ! And it really saves the day concerning all the private shaders which tab will be lost (and hard to recover) if user has to close&reopen the browser.
Alas, 10 entries is not enough (I visit way more shaders than this between 2 brower crash or computer reboot). -> would it be possible to store many more ? ( possibly keeping 10 menu items + adding an item "more" ).
thanks !

**Comment by patuwwy** [comment]
#78
