### ISSUE TITLE
suggestion: adding column keywords in profile page (shader list)

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#86]
Suggestion: 
adding a column with keywords in user private list of shader (i.e., profile page). (Probably in last position to not be annoyed with formatting.)

Motivation: 
when we have many shaders, it's very hard to find them again, especially the private & unlisted (that can't be visually browsed or searched like the public ones). Currently the only way is to use the browser search in page feature, which would be usable if more information was available there to search: for now it is only the (short) title, and the date only if it's not a private shader (these have no date). 
Adding a keywords column would help searching (using browser feature), either by theme, or even using some personally encoded keyword like DATE:2019.09 to re-find our private shaders (I better remember the month that the title).

**Comment by patuwwy** [comment]
Currently there is no way to do this - no tags data is accessible on profile page

**Comment by FabriceNeyret** [comment]
oh I see: because the page is filled via php, not via the JS api (that wouldn't see the private ones).
Too bad :-/  . Thanks for considering, anyway ! :-)

**Comment by patuwwy** [comment]
It is filled with js api but this api doesn't provide such data in this case.

**Comment by FabriceNeyret** [comment]
note that the plugin does get the info while saving all shaders. But I guess here it's at a file level, one by one, and thus ultra-slow...
