### ISSUE TITLE
[BUG] "open recent" only show mines

### ISSUE THREAD

**Issue by FabriceNeyret** [patuwwy/ShaderToy-Chrome-Plugin#90]
Hi there !
It used to work ( and I did enjoyed the new version with more items ), but right now it only show my (public) shaders, not everyone's I visited. ;-)

**Comment by patuwwy** [comment]
It is not a bug. It is expected behavior.

**Comment by patuwwy** [comment]
It shows all your shaders. Not only the public ones but you have to be logged in to shadertoy to store unlisted/private.
